# Built with Jekyll 3.2.0

# Setup
title:               'Tempting Shortcuts'
tagline:             'Working notes on the slower path'
description:         "I'm a laconic learner. This site is an attempt to rectify the former. I spend most of my time thinking about the intersection of education, technology and theology."
url:                 'http://rohan.rohanandkate.net'
baseurl:             ''

# About/contact
author:
  name:              Rohan Edmeades
  url:               https://twitter.com/redmeades
  email:             rohan@rohanandkate.net

# Permalinks

  #permalink: pretty
permalink: /:title-:year:month:day/

# Set encoding to UTF-8
encoding: utf-8

# defaults
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: page

# Collections for texts
collections:
  texts:
    output: true
  posts:
    output: true
    permalink: /b/:title-:year:month:day/
  notes:
    output: true
    permalink: /notes/:path:output_ext
  guides:
    output: true
    permalink: /guides/:path/:title:output_ext

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


